default_language_version:
  python: python3.9

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
        exclude: ^merge_sorted_files/.github/
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: .venv/bin/isort --settings-path pyproject.toml
        exclude: ^merge_sorted_files/
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: .venv/bin/black --config pyproject.toml
        exclude: ^merge_sorted_files/
        types: [python]
        language: system
